# Generated by Django 3.0.3 on 2020-02-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldHeritageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='category',
        ),
        migrations.RemoveField(
            model_name='site',
            name='states',
        ),
        migrations.AlterField(
            model_name='state',
            name='iso',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='ISO',
        ),
        migrations.AddField(
            model_name='worldheritagelist',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Site'),
        ),
        migrations.AddField(
            model_name='worldheritagelist',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.State'),
        ),
    ]
