# Generated by Django 3.0.3 on 2020-02-16 07:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Must be longer than 1 character')])),
                ('surname', models.CharField(help_text='Last Name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Must be longer than 1 character')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AutoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Nick Name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Must be longer than 1 character')])),
                ('mileage', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.MakeUser')),
            ],
        ),
    ]
