# Generated by Django 3.0.3 on 2020-02-22 07:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Must longer than 1')])),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Must longer than 1')])),
                ('weight', models.FloatField()),
                ('foods', models.CharField(max_length=50)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Breed')),
            ],
        ),
    ]
